sb: ahb_sb.h ahb_sb-test.c
	gcc -o sb -g ahb_sb-test.c
string: ahb_string.h ahb_sb-test.c
	gcc -o string -g ahb_sb-test.c
string-arena: ahb_string.h ahb_string_arena-test.c
	gcc -o string_arena -g ahb_string_arena-test.c
